services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # Add ports 67:67/udp
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/London'
      #WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - '/mnt/usb_volume/pihole:/etc/pihole'
      - '/mnt/usb_volume/dnsmasq.d/:/etc/dnsmasq.d/' 
    restart: unless-stopped
